development:
  adapter: postgresql
  encoding: unicode
  database: federacy
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: federacy_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: federacy
  pool: 5
  username: federacy
  password: INUu98sjndjUINK909jn
